### ISSUE TITLE
Scratch messages seem to not all be transmitted

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/aseba#503]
I used Scratch 3 with Windows 8.1 and Thymio Suite:
![image](https://user-images.githubusercontent.com/4930020/56267238-8b79a980-60ee-11e9-8c46-b526caf51d7e.png)
I did this program:
![image](https://user-images.githubusercontent.com/4930020/56267270-aa783b80-60ee-11e9-9ff9-8b8f2f4b0c4e.png)
and pressed the different buttons, and I have the following behaviours:

1. The robot sometimes doesn't react to the pression of a button even though you see that the button is pressed (sound + light on the button)
2. Sometimes, when you use the block "all motor speed 200", one of the motor start and not the other one or inversely if you want to stop both motors (only one stops)
3. I sometimes get lag between an action and a reaction (like ~ 100 ms) and sometimes also between two actions like if you put "all motor speed 200", one motor is turned on ~100 ms after the first one which makes it turn before going forward

I tried with Wireless Thymio and classic Thymio, Firmware 13. I see this behaviour in all cases, maybe a bit more with the Wireless one

**Comment by cbarraud** [comment]
By the way, one of our partner asked me that 20 minutes ago :) :
"In addition, do you plan to offer a way to download Scratch 3 code onto the robot so it can work offline with code from scratch? This can be super useful for customers and will solve our lagging issues and scratch bugs where some commands are being skipped over while executing... "

Would it be possible?

**Comment by mbonani** [comment]
For the first one it is strange that it is appening with a cable robot...
The second one is no.

**Comment by mbonani** [comment]
your test work fine for me but I add lot of problem with this simple code
![image](https://user-images.githubusercontent.com/1000934/56655844-2dbc0300-6694-11e9-894e-5e890873d59a.png)
also with cable robot sometime a motor do not get its normal value

**Comment by mbonani** [comment]
there was two sprites with code doing similar things  so it was a confusing test

**Comment by cor3ntin** [comment]
@mbonani how often, with what code ?

**Comment by mbonani** [comment]
in Wireless mode for me its appens 2-3% of the time that one of the motor do not get a message, it is more difficult to say when both have not react to the commend it is the button that was not correctly transmit or the two motor do not get the message.

 for me we should avoid a block sending several messages. one block= one message

**Comment by cor3ntin** [comment]
Other solutions would be to send one aseba messages for multiple events

**Comment by mbonani** [comment]
in which sense? getting the value are normally manage by the TDM, I think it make sense to get the changed value, with the new protocol but we could be more inteligent for specific events. In the other sense one scratch blocks should send an unique aseba "user" message that acts on something. If we can directly act on a variable it just send an unique "systeme message"

I just analyse more the .aesl and we can improve:

- calculation for the proximity sensor should be done under `onevent prox` [10Hz] and not `event button` [50hz] it will relaxe the VM, 
- use the math.deque (http://wiki.thymio.org/en:asebastdnativedeque) only available from firmware V11
- RGB leds as variables? (firmware V13) can we send a system message to change 3 variables or do we pass as now with user message?
- use the `onevent button.backward` and related to emit a message to say a button was pressed or relaxed, I think we missed some pressed button because TDM read at 10hz the variables and buttons are manged at 50Hz internaly so a very short pressed can be missed (probably what is happening to Christophe)

**Comment by mbonani** [comment]
most sugestion implemented in PR https://github.com/Mobsya/scratch-vm/pull/40

**Comment by cor3ntin** [comment]
Fixed ?

**Comment by mbonani** [comment]
let me test inside master :-)

**Comment by mbonani** [comment]
New version improve and fix the case for the buttons problems on cable normaly it cannot miss one.
But there is still the problem for the Wireless robot where some "user" message can be drop without preventing anything.  So sometimes a button can be push, the code emit a sound the vm send the message, but the computer do not get it in respect to the Wireless aviability.

**Comment by mbonani** [comment]
It seems to pose sometimes problem to q-motion behavior, I remember that the old code was managing that but I am not sure i is still the case

**Comment by mbonani** [comment]
I think I will open specific issue in scratch repo and close this one

**Comment by mbonani** [comment]
closing issue because reported in:
https://github.com/Mobsya/scratch-vm/issues/42
https://github.com/Mobsya/scratch-vm/issues/41
