### ISSUE TITLE
VPL sizing windows create sometimes bad proportion for the buttons 

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba#731]
<img width="640" alt="Screenshot 2019-11-29 at 18 11 05" src="https://user-images.githubusercontent.com/1000934/69947138-50957c00-14ed-11ea-9488-98830da2faba.png">

**Comment by mbonani** [comment]
it happen at least on  Macosx 10.14,

**Comment by mbonani** [comment]
on a 10.14.3 it is working
<img width="303" alt="Capture d’écran 2019-12-04 à 08 42 38" src="https://user-images.githubusercontent.com/1000934/70123405-e4dd1b80-1672-11ea-927d-fc2aa422a043.png">
<img width="509" alt="Capture d’écran 2019-12-04 à 08 39 26" src="https://user-images.githubusercontent.com/1000934/70123409-e7d80c00-1672-11ea-8ee3-3116481b10f0.png">

**Comment by mbonani** [comment]
it works on a 10.14.3 
<img width="303" alt="Capture d’écran 2019-12-04 à 08 42 38" src="https://user-images.githubusercontent.com/1000934/70123862-d17e8000-1673-11ea-9a85-1fac9c55ff4d.png">
<img width="509" alt="Capture d’écran 2019-12-04 à 08 39 26" src="https://user-images.githubusercontent.com/1000934/70123907-e5c27d00-1673-11ea-89f7-ac8c5381ed15.png">

**Comment by mbonani** [comment]
it do not work on another 10.14.x

> La résolution d’écran n’a pas d’importance. La taille verticale de la fenêtre a un minimum. Tu va à ce minimum, puis tu élargis la fenêtre. Sur un écran 
> J’arrive à voir le problème avec un écran de 1680 de large, 
<img width="1654" alt="Screenshot 2019-12-03 at 09 33 27" src="https://user-images.githubusercontent.com/1000934/70124001-1c989300-1674-11ea-909d-175afd95fc23.png">

mais avec un écran de 3008 de large les icônes disparaissent

<img width="2664" alt="Screenshot 2019-12-03 at 09 33 47" src="https://user-images.githubusercontent.com/1000934/70124041-376b0780-1674-11ea-9c2d-6d4953e6e017.png">

**Comment by mbonani** [comment]
I understand better the calclulation of the is wrong when you have a small high and a big with
![image](https://user-images.githubusercontent.com/1000934/70126064-7ac77500-1678-11ea-9853-68b6c0336e57.png)

**Comment by podak** [comment]
This issue seems to be generated by a combination of how Qt manages the resizing of elements inside QGridLayout containers and how this layout can be combined with others inside the application. In particular I tried the following things:

- Set a minimum height to both the rows of the GridLayout and the PushButton in the cells. This successfully stopped the container elements to reduce their height, but the inner icon keeps resizing until it disappear
- Set a fixed dimension to the inner icon with the setIconSize function. This apparently had no effect and the icons keep resizing.
- Isolate the problem skipping the rendering of the action/event area ( on the bottom ) and the aseba code editor ( on the right ). This somehow deactivate the defect and the icons do not disappear anymore

**Comment by mbonani** [comment]
actual version 
![Screenshot 2020-03-19 at 10 57 13](https://user-images.githubusercontent.com/1000934/78232241-3f2ca280-74d4-11ea-8a31-7f6794b67562.png)
