### ISSUE TITLE
aseba code from scratch

### ISSUE THREAD

**Issue by amryounis** [Mobsya/aseba#745]
in case of vpl or blockly, it is either the aseba code is shown or if aseba studio is run afterwards the code gets into the editor automatically. this is not the case with scratch. how to get equivalent aseba code for thymio blocks?

![image](https://user-images.githubusercontent.com/3895133/73589213-0f651c80-44dc-11ea-9511-fdfb1f3f8b13.png)

![image](https://user-images.githubusercontent.com/3895133/73589229-286dcd80-44dc-11ea-98f9-fba7d1e3b4ce.png)

**Comment by mbonani** [comment]
We do not show the code that  is coming from scratch because it is a communication protocol between scratch and Thymio. It is not representing at all the blocks that user put in scratch. Here you find the code inside Thymio that is upload when you start scratch: https://github.com/Mobsya/scratch-vm/blob/develop/src/extensions/scratch3_thymio/aesl.js
